(env
 (dev
  (flags
   (:standard -w -58))))

(library
 (name re_benchmarks)
 (modules cases http import memory_patterns tex)
 (libraries
  re_private
  base
  stdio
  ppx_expect.config
  ppx_expect.config_types
  ppx_expect_common
  ppx_inline_test.config)
 (inline_tests
  (deps
   benchmarks/files
   benchmarks/http-requests.txt
   benchmarks/tex.gitignore))
 (preprocess
  (pps ppx_expect)))

;; The inline-test runner starts in this directory, while the benchmark inputs
;; use paths relative to the project root.

(subdir
 benchmarks
 (copy_files ../{files,http-requests.txt,tex.gitignore}))

(executable
 (enabled_if
  (not %{env:CI=false}))
 (libraries
  re_benchmarks
  re
  re_private
  core
  base
  stdio
  threads
  core_bench
  core_unix.command_unix
  memtrace)
 (modules benchmark memory id_sets)
 (name benchmark))

(rule
 (alias runtest)
 (enabled_if
  (not %{env:CI=false}))
 (deps files http-requests.txt tex.gitignore)
 (action
  (chdir
   %{workspace_root}
   (setenv
    RE_BENCH_FILTER
    http
    (ignore-stdout
     (run %{exe:benchmark.exe} -thin-overhead 1))))))

(rule
 (alias runtest)
 (enabled_if
  (not %{env:CI=false}))
 (deps files http-requests.txt tex.gitignore)
 (action
  (chdir
   %{workspace_root}
   (setenv
    RE_BENCH_FILTER
    "expression IDs/broad/16/1024,expression IDs/narrow/1024"
    (ignore-stdout
     (run %{exe:benchmark.exe} -thin-overhead 1))))))

(executable
 (enabled_if
  (not %{env:CI=false}))
 (name compare)
 (modules compare)
 (libraries
  core
  csv
  base
  core_unix
  core_unix.command_unix
  core_unix.filename_unix
  spawn
  stdio
  sexplib))
