name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.x'

      - name: Pin
        run: opam pin -n .

      - name: Depext
        run: opam depext -yt re

      - name: Deps
        run: opam install -d . --deps-only
        run: opam install odoc

      - name: Build
        run: opam exec -- dune build @doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html/
          destination_dir: .
          enable_jekyll: true
